##############################
#########SERVICES#############
##############################

services:    
  jenkins:
    extends:
      file: jenkins.yml
      service: jenkins

##############################
##########VOLUMES############# 
############################## 

volumes:
  jenkins_data:
    external: true

##############################
##########NETWORK#############
##############################

networks:
  jenkins-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.28.50.0/24"
          gateway: "172.28.50.1"

