services:
  jenkins:
    image: 'jenkins/jenkins:lts-jdk11'
    container_name: jenkins
    user: root
    privileged: true
    volumes:
      - jenkins_data:/var/jenkins_data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    networks:
      - jenkins-net
    ports:
      - '8082:8080'
      - '50000:50000'
    restart: unless-stopped
    
